[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
src_dir = main
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
lib_deps =
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit ADS1X15
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    mikalhart/TinyGPSPlus
    sandeepmistry/LoRa
    paulstoffregen/OneWire
    milesburton/DallasTemperature
