#ifndef SANKATNET_GATEWAY_CONFIG_H
#define SANKATNET_GATEWAY_CONFIG_H

#include <Arduino.h>

namespace GatewayConfig {

/*
 * ============================================================
 * Gateway Identity
 * ============================================================
 */

static constexpr uint16_t GATEWAY_ID   = 0xFFFF;
static constexpr uint16_t BROADCAST_ID = 0xFFFE;


/*
 * ============================================================
 * Hardware
 * ============================================================
 *
 * The gateway uses:
 *
 *   ESP32
 *   SX1278 LoRa
 *   Wi-Fi
 *
 * Pin assignments for SX1278 remain in:
 *
 *   config/PinConfig.h
 *
 * No OLED is used.
 * ============================================================
 */


/*
 * ============================================================
 * LoRa Configuration
 * ============================================================
 */

static constexpr uint32_t LORA_FREQUENCY = 433E6;

static constexpr uint8_t LORA_SPREADING_FACTOR = 9;

static constexpr uint8_t LORA_CODING_RATE = 5;

static constexpr uint32_t LORA_BANDWIDTH = 125E3;

static constexpr uint8_t LORA_SYNC_WORD = 0x12;

static constexpr int8_t LORA_TX_POWER = 17;

static constexpr uint16_t LORA_PREAMBLE_LENGTH = 8;

static constexpr bool LORA_ENABLE_CRC = true;


/*
 * Maximum LoRa frame accepted by the gateway.
 */

static constexpr uint16_t MAX_LORA_PACKET_SIZE = 220;


/*
 * ============================================================
 * Internet / Wi-Fi
 * ============================================================
 *
 * Credentials should NOT be hard-coded in this file.
 *
 * Wi-FiManager is responsible for obtaining credentials from
 * the configured secure storage / build configuration.
 * ============================================================
 */

static constexpr uint32_t WIFI_CONNECT_TIMEOUT_MS = 15000;

static constexpr uint32_t WIFI_RECONNECT_INTERVAL_MS = 5000;


/*
 * ============================================================
 * MQTT
 * ============================================================
 */

static constexpr uint16_t MQTT_PORT = 8883;


/*
 * MQTT keep-alive interval.
 */

static constexpr uint16_t MQTT_KEEP_ALIVE_SECONDS = 60;


/*
 * MQTT connection timeout.
 */

static constexpr uint32_t MQTT_CONNECT_TIMEOUT_MS = 10000;


/*
 * Reconnection interval.
 */

static constexpr uint32_t MQTT_RECONNECT_INTERVAL_MS = 5000;


/*
 * Maximum MQTT payload generated by the gateway.
 */

static constexpr uint16_t MQTT_MAX_PAYLOAD_SIZE = 2048;


/*
 * ============================================================
 * MQTT Topics
 * ============================================================
 */

static constexpr const char *MQTT_TOPIC_ROOT =
    "sankatnet";


static constexpr const char *MQTT_TOPIC_TELEMETRY =
    "sankatnet/telemetry";


static constexpr const char *MQTT_TOPIC_ALERTS =
    "sankatnet/alerts";


static constexpr const char *MQTT_TOPIC_HEARTBEAT =
    "sankatnet/heartbeat";


static constexpr const char *MQTT_TOPIC_ROUTE =
    "sankatnet/route";


static constexpr const char *MQTT_TOPIC_DISCOVERY =
    "sankatnet/discovery";


static constexpr const char *MQTT_TOPIC_CONFIG =
    "sankatnet/config";


static constexpr const char *MQTT_TOPIC_GATEWAY_STATUS =
    "sankatnet/gateway/status";


static constexpr const char *MQTT_TOPIC_GATEWAY_HEALTH =
    "sankatnet/gateway/health";


static constexpr const char *MQTT_TOPIC_COMMAND =
    "sankatnet/command";


/*
 * ============================================================
 * MQTT Quality of Service
 * ============================================================
 *
 * Telemetry:
 *   QoS 1
 *
 * Critical alerts:
 *   QoS 1
 *
 * Heartbeat:
 *   QoS 0
 *
 * Gateway status:
 *   QoS 1
 * ============================================================
 */

static constexpr uint8_t MQTT_QOS_TELEMETRY = 1;

static constexpr uint8_t MQTT_QOS_ALERT = 1;

static constexpr uint8_t MQTT_QOS_HEARTBEAT = 0;

static constexpr uint8_t MQTT_QOS_GATEWAY = 1;


/*
 * ============================================================
 * MQTT Retain Policy
 * ============================================================
 *
 * Telemetry and alerts should not normally be retained.
 *
 * Gateway status can be retained so a newly connected backend
 * can immediately obtain the latest gateway state.
 * ============================================================
 */

static constexpr bool MQTT_RETAIN_TELEMETRY = false;

static constexpr bool MQTT_RETAIN_ALERT = false;

static constexpr bool MQTT_RETAIN_HEARTBEAT = false;

static constexpr bool MQTT_RETAIN_GATEWAY_STATUS = true;


/*
 * ============================================================
 * Backend Queue
 * ============================================================
 *
 * The gateway must continue receiving LoRa packets even when
 * the Internet connection is unavailable.
 *
 * Queued packets are uploaded after MQTT reconnects.
 * ============================================================
 */

static constexpr uint16_t GATEWAY_QUEUE_SIZE = 64;

static constexpr uint32_t QUEUE_MAX_PACKET_AGE_MS =
    30UL * 60UL * 1000UL;


/*
 * Number of queued packets processed in one cycle.
 */

static constexpr uint8_t QUEUE_BATCH_SIZE = 4;


/*
 * Queue processing interval.
 */

static constexpr uint32_t QUEUE_PROCESS_INTERVAL_MS = 1000;


/*
 * ============================================================
 * Network Maintenance
 * ============================================================
 */

static constexpr uint32_t NETWORK_CHECK_INTERVAL_MS = 5000;


/*
 * ============================================================
 * Gateway Heartbeat
 * ============================================================
 */

static constexpr uint32_t GATEWAY_HEARTBEAT_INTERVAL_MS =
    30000;


/*
 * ============================================================
 * Health Monitoring
 * ============================================================
 */

static constexpr uint32_t HEALTH_CHECK_INTERVAL_MS =
    10000;


/*
 * ============================================================
 * MQTT Message Limits
 * ============================================================
 */

static constexpr uint16_t MAX_NODE_ID_LENGTH = 12;

static constexpr uint16_t MAX_TOPIC_LENGTH = 128;


/*
 * ============================================================
 * Backend Buffering
 * ============================================================
 */

static constexpr uint8_t MAX_PUBLISH_RETRIES = 3;

static constexpr uint32_t PUBLISH_RETRY_DELAY_MS = 500;


/*
 * ============================================================
 * Gateway Operating Modes
 * ============================================================
 */

enum GatewayMode : uint8_t
{
    MODE_STARTING = 0,
    MODE_ONLINE,
    MODE_OFFLINE,
    MODE_DEGRADED,
    MODE_ERROR
};


/*
 * ============================================================
 * Internet State
 * ============================================================
 */

enum InternetState : uint8_t
{
    INTERNET_DISCONNECTED = 0,
    INTERNET_WIFI_CONNECTED,
    INTERNET_MQTT_CONNECTED
};


/*
 * ============================================================
 * Gateway Features
 * ============================================================
 */

static constexpr bool ENABLE_LORA_MESH = true;

static constexpr bool ENABLE_MQTT = true;

static constexpr bool ENABLE_MQTT_TLS = true;

static constexpr bool ENABLE_STORE_FORWARD = true;

static constexpr bool ENABLE_GATEWAY_HEARTBEAT = true;

static constexpr bool ENABLE_BACKEND_PUBLISH = true;


/*
 * ============================================================
 * Security Policy
 * ============================================================
 *
 * LoRa packets are required to use the security system defined
 * in SecurityConfig.h.
 *
 * MQTT communication must use TLS in deployment.
 * ============================================================
 */

static constexpr bool REQUIRE_LORA_ENCRYPTION = true;

static constexpr bool REQUIRE_MQTT_TLS = true;


/*
 * ============================================================
 * Configuration Validation
 * ============================================================
 */

static_assert(
    GATEWAY_ID == 0xFFFF,
    "Gateway ID must remain 0xFFFF"
);

static_assert(
    BROADCAST_ID == 0xFFFE,
    "Broadcast ID must remain 0xFFFE"
);

static_assert(
    MAX_LORA_PACKET_SIZE >= 64,
    "LoRa packet buffer is too small"
);

static_assert(
    GATEWAY_QUEUE_SIZE > 0,
    "Gateway queue must contain at least one entry"
);

static_assert(
    QUEUE_BATCH_SIZE > 0,
    "Queue batch size must be greater than zero"
);

static_assert(
    MQTT_PORT == 8883,
    "Gateway MQTT must use the TLS port"
);

static_assert(
    REQUIRE_LORA_ENCRYPTION,
    "Unauthenticated LoRa communication is not permitted"
);

static_assert(
    REQUIRE_MQTT_TLS,
    "Unencrypted MQTT is not permitted"
);

} // namespace GatewayConfig

#endif